import assert from 'node:assert/strict';
import {dailyAttendance,monthlyWorkbook} from '../worker/index.js';
const workers=[{id:'w1',name:'Worker One',role:'Labourer',rate:60000,attendance_start:'2026-10-01'},{id:'w2',name:'New Worker',role:'Labourer',rate:80000,attendance_start:'2026-10-05'}];
const attendance=[{id:'a1',worker:'w1',date:'2026-10-01',site:'s1',units:2,rate:60000,ot_hours:2,marked_by:'supervisor-one'}];
assert.equal(dailyAttendance(workers,attendance,'2026-10-01','2026-10-05').length,1,'New worker must not be marked absent before joining');
const missing=dailyAttendance(workers,attendance,'2026-10-05','2026-10-05');
assert.equal(missing.length,2);
assert.ok(missing.every(a=>a.automatic&&a.units===0&&a.ot_hours===0&&a.site===null&&a.id===null&&a.marked_by===null));
assert.equal(dailyAttendance(workers,attendance,'2026-10-06','2026-10-05').length,0,'Future days are not automatic absences');
assert.equal(dailyAttendance(workers,attendance,'2026-02-30','2026-10-05').length,0,'Invalid days excluded');
attendance.push({id:'a2',worker:'w1',date:'2026-10-05',site:'s2',units:1,rate:60000,ot_hours:1,marked_by:'supervisor-two'});
const updated=dailyAttendance(workers,attendance,'2026-10-05','2026-10-05');
assert.equal(updated.filter(a=>a.automatic).length,1);
assert.equal(updated.find(a=>a.worker==='w1').marked_by,'supervisor-two','Later supervisor attendance replaces the automatic display');
assert.equal(attendance.length,2,'Automatic absences never claim or mutate saved attendance');
const workbook=Buffer.from(monthlyWorkbook({workers,attendance,sites:[],payments:[]},'2026-10')).toString('utf8');
assert.ok(workbook.includes('Absent · not filled'));
assert.ok(workbook.includes('Supervisor username'));
assert.ok(workbook.includes('supervisor-two'));
console.log('PASS: unfilled days are absent with zero wages/OT, no absence before joining or future dates, later attendance replaces defaults, Excel includes supervisor usernames.');
