import{DatabaseSync}from'node:sqlite';import{readFileSync,readdirSync}from'node:fs';import assert from'node:assert/strict';import vm from'node:vm';import worker from'../worker/index.js';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(q){let args=[];return{bind(...v){args=v;return this},async run(){return sql.prepare(q).run(...args)},async all(){return{results:sql.prepare(q).all(...args)}},async first(){return sql.prepare(q).get(...args)}}},async batch(ss){sql.exec('BEGIN');try{const r=await Promise.all(ss.map(s=>s.run()));sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
const credentials=JSON.parse(readFileSync(0,'utf8'));const owner={username:credentials.admin.username},supervisor={username:credentials.supervisor.username},other={username:'unknown'};
async function call(user,path,body){const headers={'Origin':'https://test.local','Content-Type':'application/json'};if(user?.cookie)headers.Cookie=user.cookie;const r=await worker.fetch(new Request('https://test.local/api/'+path,{headers,...(body?{method:'POST',body:JSON.stringify(body)}:{})}),{DB});return{status:r.status,cookie:r.headers.get('Set-Cookie'),...await r.json()};}
for(const [user,creds]of [[owner,credentials.admin],[supervisor,credentials.supervisor]]){const result=await call(null,'login',creds);assert.equal(result.ok,true);assert.ok(result.cookie.includes('HttpOnly'));assert.ok(result.cookie.includes('Secure'));user.cookie=result.cookie.split(';')[0];}
assert.equal((await call(null,'login',{username:owner.username,password:'incorrect-password'})).status,401);
assert.equal((await call(null,'data')).status,401);assert.equal((await call(other,'data')).status,401);assert.equal((await call(owner,'data')).user.role,'admin');
assert.equal((await call(owner,'members',{username:supervisor.username,role:'supervisor'})).ok,true);
const w=await call(owner,'workers',{name:'Ramesh',role:'Labourer',rate:60000});assert.equal(w.ok,true);const site=await call(owner,'sites',{name:'Solar site'});
assert.equal((await call(supervisor,'attendance',{date:'2026-10-02',entries:[{worker:w.id,site:site.id,units:2,otHours:2,rate:1}]})).ok,true);
const p=await call(owner,'payments',{worker:w.id,date:'2026-10-02',amount:10000,kind:'Advance',note:'Private travel note'});assert.equal(p.ok,true);
for(const path of ['workers','sites','payments','members','payments/delete'])assert.equal((await call(supervisor,path,{id:p.id,username:supervisor.username,role:'admin'})).status,403);
let d=await call(supervisor,'data');assert.equal(d.user.role,'supervisor');assert.equal(d.payments.length,0);assert.equal(d.members.length,0);assert.ok(!('rate'in d.workers[0]));assert.ok(!('rate'in d.attendance[0]));assert.ok(!JSON.stringify(d).includes('Private travel note'));
assert.equal((await call(owner,'payments',{id:p.id,worker:w.id,date:'2026-10-02',amount:25000,kind:'Advance',note:'Updated note'})).ok,true);
assert.equal((await call(owner,'workers',{id:w.id,name:'Ramesh Patel',role:'Electrician',rate:70000})).ok,true);
assert.equal((await call(owner,'sites',{id:site.id,name:'Battery site'})).ok,true);
let a=await call(owner,'data');assert.equal(a.payments.length,1);assert.equal(a.payments[0].amount,25000);assert.equal(a.payments[0].note,'Updated note');assert.equal(a.attendance[0].rate,60000);assert.equal(a.workers[0].rate,70000);
const html=await(await worker.fetch(new Request('https://test.local/'),{DB})).text();const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
async function render(payload){const nodes={};const get=id=>nodes[id]??={value:'',innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){},toggle(){}},showModal(){},close(){}};const context=vm.createContext({document:{getElementById:get,querySelectorAll:()=>[],addEventListener(){},body:{dataset:{}},modelContext:null},Intl,Date,Number,Array,Object,String,Promise,console,fetch:async()=>({ok:true,json:async()=>payload})});vm.runInContext(script,context);await new Promise(r=>setTimeout(r,5));return{nodes,context};}
let ui=await render(d);assert.ok(!ui.nodes['attendance-table'].innerHTML.includes('Daily wage'));assert.ok(!ui.nodes['attendance-table'].innerHTML.includes('Day earnings'));assert.equal(ui.nodes['payment-table'].innerHTML,'');assert.equal(vm.runInContext('isAdmin()',ui.context),false);
ui=await render(a);assert.ok(ui.nodes['payment-table'].innerHTML.includes('data-edit="payment"'));assert.ok(ui.nodes['worker-table'].innerHTML.includes('data-edit="worker"'));assert.equal(vm.runInContext('totals(data.workers[0]).earned-totals(data.workers[0]).paid',ui.context),55000);vm.runInContext('openPayment(data.payments[0].id)',ui.context);assert.equal(ui.nodes['payment-amount'].value,250);assert.equal(ui.nodes['payment-note'].value,'Updated note');
assert.equal((await call(owner,'members',{username:owner.username,role:'supervisor'})).status,403);assert.equal((await call(owner,'members',{username:supervisor.username,role:'revoked'})).ok,true);assert.equal((await call(supervisor,'data')).status,401);assert.equal((await call(supervisor,'attendance',{})).status,401);
console.log('PASS: authentication, restricted supervisor reads/writes, admin edits, preserved wage history, correct balances, role revocation and role-specific UI.');

assert.equal((await call(owner,'logout',{})).ok,true);assert.equal((await call(owner,'data')).status,401);
for(let i=0;i<5;i++)await call(null,'login',{username:'invalid-user',password:'wrong'});assert.equal((await call(null,'login',{username:'invalid-user',password:'wrong'})).status,429);
console.log('PASS: requested logins, secure sessions, invalid passwords, logout and login rate limiting.');
